# Generated by Django 4.2 on 2023-06-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_rename_spell_desc_spell_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AddField(
            model_name='spell',
            name='classes',
            field=models.ManyToManyField(to='spells.classes'),
        ),
    ]
